# Generated by Django 4.1.7 on 2023-04-07 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('idcargo', models.BigAutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=50, null=True, verbose_name='Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo')),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Sueldo')),
                ('activo', models.BooleanField(verbose_name='Activo')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.cargo')),
            ],
        ),
    ]
